### ISSUE TITLE
Just a question.

### ISSUE THREAD

**Issue by Simoncl** [nvpro-samples/gl_occlusion_culling#2]
In the scene vertex shader the matrices are accessed by the index and the byte offset.
texelFetch(tex,idx*4 + 0)
but in the raster shader, the matrices are indexed with additional offsets. As far as I can tell the matrix buffer is constructed the same. What does the following mean in the raster vert shader?
#ifndef MATRIX_WORLD
#define MATRIX_WORLD    0
#endif

#ifndef MATRIX_WORLD_IT
#define MATRIX_WORLD_IT 1
#endif

#ifndef MATRICES
#define MATRICES        2
#endif

And the index is constructed  int matindex = (matrixIndex * MATRICES + MATRIX_WORLD_IT) * 4;

I don't understand how this works when it looks like the same matrix buffer is used for both shaders?
I appreciate any insights. 

Cheers

Simon

**Comment by Simoncl** [comment]
I see you have two matrices per instance. Still confused that in the scene vert shader you don't have to stride over the inverse transpose matrix.

**Comment by pixeljetstream** [comment]
Actually the stride is done, just not using the defines
in scene.vert.glsl:

`getMatrix(texMatrices, matrixIndex*2+0)`
the `* 2 + 0` is behaving just like `matrixIndex * MATRICES + MATRIX_WORLD`
and the `* 4` is now part of the getMatrix function
