### ISSUE TITLE
Use computer shader instead of geometry

### ISSUE THREAD

**Issue by happydpc** [nvpro-samples/gl_occlusion_culling#3]
As we know, The geometry shader is not that fast as a computer shader. I have an idea, if we calculate the three edges every instance in computer shader, then it can gain more performance. I plan to implement this by Vulkan. So could this algorithm be used in that way? 

Another question is that what's the difference between these 3 sides to just drawing bounding box sides for early fragment test.

Thank you.

**Comment by pixeljetstream** [comment]
the performance of the geometry shader varies greatly on hardware/vendor and what exactly you are doing with it. In this case as each instanced geometry shader only outputs a quad per vertex, which is a fixed/low expansion that the geometry shader isn't actually too bad at (on NVIDIA hardware). A compute shader approach would mean having to write out all vertices again, just to read them during rasterization. With geometry shader or the newer mesh shader you don't write out data to memory in full, but directly output it being consumed by rasterizer. 

Another alternative is to use a vertex shader and use gl_VertexID to figure out which part of the box you are.
